import type { Metadata } from "next";
import '../globals.css'
import { div } from "framer-motion/client";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function EditorLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
       <div className={`bg-[url('/wall2.png')] antialiased bg-cover bg-no-repeat bg-center h-screen w-screen overflow-hidden`}
      >
        {children}
        </div>
   
  );
}
